export interface DataItem {
  id: string;
  title: string;
  cover: Image;
  created_at: string;
  description: string;
  banner_assets: Image[];
  is_active: boolean;
  submit_to_marketplace: boolean;
  approved_to_marketplace: boolean | null;
  country: string;
  default_currency: string;
  default_variant: Variant;
  variants: Variant[];
  default_extra_details: ExtraDetails;
  category: { id: string; name: string };
  custom_fields: { [x: string]: any }[];
  related_products: string[];
  hustle: { name: string };
}

interface Variant {
  selling_price: { [x: string]: number };
  actual_price: { [x: string]: number };
  stock: number;
  available_stock: number;
  actual_stock: number;
  baseline_stock: number;
  description: string;
  title: string;
  is_free: boolean;
  edit: boolean;
  id: string;
  extra_details: ExtraDetails & {
    type: string;
    is_complimentary: boolean;
  };
}

interface ExtraDetails {
  venue: string;
  end_date: string;
  end_time: string;
  timezone: string;
  start_date: string;
  start_time: string;
  coordinates: string;
  no_per_purchase: number;
}

interface Image {
  type: string;
  url: string;
}

export const dummyDataItems: DataItem[] = [
  {
    id: '1',
    title: 'Summer Music Festival',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Summer+Music+Festival' },
    created_at: '2024-01-15T10:00:00Z',
    description: 'Annual summer music festival featuring top artists',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Music+Festival+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'USA',
    default_currency: 'USD',
    default_variant: {
      selling_price: { USD: 99.99 },
      actual_price: { USD: 149.99 },
      stock: 500,
      available_stock: 450,
      actual_stock: 500,
      baseline_stock: 1000,
      description: 'General admission',
      title: 'GA Ticket',
      is_free: false,
      edit: true,
      id: 'v1',
      extra_details: {
        venue: 'Central Park',
        end_date: '2024-07-15',
        end_time: '22:00',
        timezone: 'EST',
        start_date: '2024-07-14',
        start_time: '18:00',
        coordinates: '40.7829,-73.9654',
        no_per_purchase: 4,
        type: 'event',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Central Park',
      end_date: '2024-07-15',
      end_time: '22:00',
      timezone: 'EST',
      start_date: '2024-07-14',
      start_time: '18:00',
      coordinates: '40.7829,-73.9654',
      no_per_purchase: 4,
    },
    category: { id: 'cat1', name: 'Music Events' },
    custom_fields: [{ field: 'artist_count', value: 25 }],
    related_products: ['2', '3'],
    hustle: { name: 'Event Hustlers Inc' },
  },
  {
    id: '2',
    title: 'Tech Conference 2024',
    cover: { type: 'image/png', url: 'https://placehold.co/600x400?text=Tech+Conference' },
    created_at: '2024-02-01T08:30:00Z',
    description: 'Leading technology conference with industry experts',
    banner_assets: [{ type: 'image/png', url: 'https://placehold.co/1200x400?text=Tech+Conference+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'UK',
    default_currency: 'GBP',
    default_variant: {
      selling_price: { GBP: 199.99 },
      actual_price: { GBP: 299.99 },
      stock: 1000,
      available_stock: 800,
      actual_stock: 1000,
      baseline_stock: 2000,
      description: 'Standard pass',
      title: 'Conference Pass',
      is_free: false,
      edit: true,
      id: 'v2',
      extra_details: {
        venue: 'ExCel London',
        end_date: '2024-05-10',
        end_time: '17:00',
        timezone: 'GMT',
        start_date: '2024-05-08',
        start_time: '09:00',
        coordinates: '51.5085,-0.0270',
        no_per_purchase: 1,
        type: 'conference',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'ExCel London',
      end_date: '2024-05-10',
      end_time: '17:00',
      timezone: 'GMT',
      start_date: '2024-05-08',
      start_time: '09:00',
      coordinates: '51.5085,-0.0270',
      no_per_purchase: 1,
    },
    category: { id: 'cat2', name: 'Tech Events' },
    custom_fields: [{ field: 'speaker_count', value: 50 }],
    related_products: ['3'],
    hustle: { name: 'Tech Events Ltd' },
  },
  {
    id: '3',
    title: 'Yoga Retreat Weekend',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Yoga+Retreat' },
    created_at: '2024-03-10T14:20:00Z',
    description: 'Relaxing yoga retreat in nature',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Yoga+Retreat+Banner' }],
    is_active: true,
    submit_to_marketplace: false,
    approved_to_marketplace: false,
    country: 'Canada',
    default_currency: 'CAD',
    default_variant: {
      selling_price: { CAD: 249.99 },
      actual_price: { CAD: 349.99 },
      stock: 200,
      available_stock: 150,
      actual_stock: 200,
      baseline_stock: 300,
      description: 'Weekend package with meals',
      title: 'Yoga Weekend',
      is_free: false,
      edit: true,
      id: 'v3',
      extra_details: {
        venue: 'Banff National Park',
        end_date: '2024-06-16',
        end_time: '14:00',
        timezone: 'MST',
        start_date: '2024-06-14',
        start_time: '10:00',
        coordinates: '51.1694,-115.5708',
        no_per_purchase: 2,
        type: 'wellness',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Banff National Park',
      end_date: '2024-06-16',
      end_time: '14:00',
      timezone: 'MST',
      start_date: '2024-06-14',
      start_time: '10:00',
      coordinates: '51.1694,-115.5708',
      no_per_purchase: 2,
    },
    category: { id: 'cat3', name: 'Wellness' },
    custom_fields: [{ field: 'instructor_count', value: 5 }],
    related_products: [],
    hustle: { name: 'Wellness Co' },
  },
  {
    id: '4',
    title: 'Startup Pitch Competition',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Startup+Pitch' },
    created_at: '2024-01-20T11:45:00Z',
    description: 'Annual competition for innovative startups',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Startup+Competition+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'Singapore',
    default_currency: 'SGD',
    default_variant: {
      selling_price: { SGD: 49.99 },
      actual_price: { SGD: 79.99 },
      stock: 300,
      available_stock: 280,
      actual_stock: 300,
      baseline_stock: 500,
      description: 'Spectator ticket',
      title: 'Pitch Competition Ticket',
      is_free: false,
      edit: true,
      id: 'v4',
      extra_details: {
        venue: 'Singapore Convention Centre',
        end_date: '2024-04-20',
        end_time: '18:00',
        timezone: 'SGT',
        start_date: '2024-04-20',
        start_time: '14:00',
        coordinates: '1.3521,103.8198',
        no_per_purchase: 3,
        type: 'business',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Singapore Convention Centre',
      end_date: '2024-04-20',
      end_time: '18:00',
      timezone: 'SGT',
      start_date: '2024-04-20',
      start_time: '14:00',
      coordinates: '1.3521,103.8198',
      no_per_purchase: 3,
    },
    category: { id: 'cat4', name: 'Business Events' },
    custom_fields: [{ field: 'prize_pool', value: 100000 }],
    related_products: ['5'],
    hustle: { name: 'StartupHub Asia' },
  },
  {
    id: '5',
    title: 'Art Exhibition Opening',
    cover: { type: 'image/png', url: 'https://placehold.co/600x400?text=Art+Exhibition' },
    created_at: '2024-02-14T09:15:00Z',
    description: 'Contemporary art exhibition featuring emerging artists',
    banner_assets: [{ type: 'image/png', url: 'https://placehold.co/1200x400?text=Art+Exhibition+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'France',
    default_currency: 'EUR',
    default_variant: {
      selling_price: { EUR: 15.99 },
      actual_price: { EUR: 25.99 },
      stock: 400,
      available_stock: 350,
      actual_stock: 400,
      baseline_stock: 600,
      description: 'General admission',
      title: 'Exhibition Ticket',
      is_free: false,
      edit: true,
      id: 'v5',
      extra_details: {
        venue: 'Louvre Paris',
        end_date: '2024-08-31',
        end_time: '18:00',
        timezone: 'CET',
        start_date: '2024-06-01',
        start_time: '10:00',
        coordinates: '48.8607,2.3361',
        no_per_purchase: 2,
        type: 'art',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Louvre Paris',
      end_date: '2024-08-31',
      end_time: '18:00',
      timezone: 'CET',
      start_date: '2024-06-01',
      start_time: '10:00',
      coordinates: '48.8607,2.3361',
      no_per_purchase: 2,
    },
    category: { id: 'cat5', name: 'Art Events' },
    custom_fields: [{ field: 'artist_count', value: 15 }],
    related_products: [],
    hustle: { name: 'Art Collective Paris' },
  },
  {
    id: '6',
    title: 'Marathon Run 2024',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Marathon+Run' },
    created_at: '2024-01-25T13:00:00Z',
    description: 'Annual city marathon event',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Marathon+Banner' }],
    is_active: false,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'Australia',
    default_currency: 'AUD',
    default_variant: {
      selling_price: { AUD: 79.99 },
      actual_price: { AUD: 119.99 },
      stock: 5000,
      available_stock: 4200,
      actual_stock: 5000,
      baseline_stock: 10000,
      description: 'Marathon entry',
      title: 'Marathon Registration',
      is_free: false,
      edit: true,
      id: 'v6',
      extra_details: {
        venue: 'Melbourne CBD',
        end_date: '2024-10-13',
        end_time: '13:00',
        timezone: 'AEST',
        start_date: '2024-10-13',
        start_time: '06:00',
        coordinates: '-37.8136,144.9631',
        no_per_purchase: 1,
        type: 'sports',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Melbourne CBD',
      end_date: '2024-10-13',
      end_time: '13:00',
      timezone: 'AEST',
      start_date: '2024-10-13',
      start_time: '06:00',
      coordinates: '-37.8136,144.9631',
      no_per_purchase: 1,
    },
    category: { id: 'cat6', name: 'Sports Events' },
    custom_fields: [{ field: 'distance_km', value: 42.2 }],
    related_products: ['7'],
    hustle: { name: 'Sports Events Australia' },
  },
  {
    id: '7',
    title: 'Cooking Class Series',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Cooking+Class' },
    created_at: '2024-03-05T10:30:00Z',
    description: 'Learn international cuisines from master chefs',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Cooking+Class+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: false,
    country: 'Italy',
    default_currency: 'EUR',
    default_variant: {
      selling_price: { EUR: 89.99 },
      actual_price: { EUR: 129.99 },
      stock: 100,
      available_stock: 60,
      actual_stock: 100,
      baseline_stock: 150,
      description: '4-class series',
      title: 'Cooking Class',
      is_free: false,
      edit: true,
      id: 'v7',
      extra_details: {
        venue: 'Rome Cooking Studio',
        end_date: '2024-07-15',
        end_time: '14:00',
        timezone: 'CET',
        start_date: '2024-06-15',
        start_time: '10:00',
        coordinates: '41.9028,12.4964',
        no_per_purchase: 1,
        type: 'culinary',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Rome Cooking Studio',
      end_date: '2024-07-15',
      end_time: '14:00',
      timezone: 'CET',
      start_date: '2024-06-15',
      start_time: '10:00',
      coordinates: '41.9028,12.4964',
      no_per_purchase: 1,
    },
    category: { id: 'cat7', name: 'Culinary Events' },
    custom_fields: [{ field: 'chef_name', value: 'Marco Rossi' }],
    related_products: [],
    hustle: { name: 'Culinary Institute Italy' },
  },
  {
    id: '8',
    title: 'Film Festival 2024',
    cover: { type: 'image/png', url: 'https://placehold.co/600x400?text=Film+Festival' },
    created_at: '2024-02-20T16:45:00Z',
    description: 'International film festival showcasing indie and mainstream films',
    banner_assets: [{ type: 'image/png', url: 'https://placehold.co/1200x400?text=Film+Festival+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'Germany',
    default_currency: 'EUR',
    default_variant: {
      selling_price: { EUR: 12.99 },
      actual_price: { EUR: 18.99 },
      stock: 1000,
      available_stock: 750,
      actual_stock: 1000,
      baseline_stock: 1500,
      description: 'Single screening',
      title: 'Film Ticket',
      is_free: false,
      edit: true,
      id: 'v8',
      extra_details: {
        venue: 'Berlin Film Palace',
        end_date: '2024-09-30',
        end_time: '22:00',
        timezone: 'CET',
        start_date: '2024-09-20',
        start_time: '18:00',
        coordinates: '52.5200,13.4050',
        no_per_purchase: 4,
        type: 'entertainment',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Berlin Film Palace',
      end_date: '2024-09-30',
      end_time: '22:00',
      timezone: 'CET',
      start_date: '2024-09-20',
      start_time: '18:00',
      coordinates: '52.5200,13.4050',
      no_per_purchase: 4,
    },
    category: { id: 'cat8', name: 'Film Events' },
    custom_fields: [{ field: 'film_count', value: 45 }],
    related_products: ['9'],
    hustle: { name: 'Berlin Film Festival' },
  },
  {
    id: '9',
    title: 'Wedding Expo',
    cover: { type: 'image/jpeg', url: 'https://placehold.co/600x400?text=Wedding+Expo' },
    created_at: '2024-03-12T11:20:00Z',
    description: 'Comprehensive wedding planning and vendor expo',
    banner_assets: [{ type: 'image/jpeg', url: 'https://placehold.co/1200x400?text=Wedding+Expo+Banner' }],
    is_active: true,
    submit_to_marketplace: false,
    approved_to_marketplace: false,
    country: 'USA',
    default_currency: 'USD',
    default_variant: {
      selling_price: { USD: 25.99 },
      actual_price: { USD: 39.99 },
      stock: 800,
      available_stock: 650,
      actual_stock: 800,
      baseline_stock: 1200,
      description: 'Couple admission',
      title: 'Expo Ticket',
      is_free: false,
      edit: true,
      id: 'v9',
      extra_details: {
        venue: 'Los Angeles Convention Center',
        end_date: '2024-05-19',
        end_time: '17:00',
        timezone: 'PST',
        start_date: '2024-05-18',
        start_time: '10:00',
        coordinates: '34.4159,-118.2679',
        no_per_purchase: 2,
        type: 'wedding',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Los Angeles Convention Center',
      end_date: '2024-05-19',
      end_time: '17:00',
      timezone: 'PST',
      start_date: '2024-05-18',
      start_time: '10:00',
      coordinates: '34.4159,-118.2679',
      no_per_purchase: 2,
    },
    category: { id: 'cat9', name: 'Weddings' },
    custom_fields: [{ field: 'vendor_count', value: 100 }],
    related_products: [],
    hustle: { name: 'Wedding Events USA' },
  },
  {
    id: '10',
    title: 'Science Symposium',
    cover: { type: 'image/png', url: 'https://placehold.co/600x400?text=Science+Symposium' },
    created_at: '2024-01-30T15:50:00Z',
    description: 'Annual symposium bringing together leading scientists and researchers',
    banner_assets: [{ type: 'image/png', url: 'https://placehold.co/1200x400?text=Science+Symposium+Banner' }],
    is_active: true,
    submit_to_marketplace: true,
    approved_to_marketplace: true,
    country: 'Japan',
    default_currency: 'JPY',
    default_variant: {
      selling_price: { JPY: 12000 },
      actual_price: { JPY: 18000 },
      stock: 600,
      available_stock: 540,
      actual_stock: 600,
      baseline_stock: 1000,
      description: '3-day access',
      title: 'Symposium Pass',
      is_free: false,
      edit: true,
      id: 'v10',
      extra_details: {
        venue: 'Tokyo Science Hall',
        end_date: '2024-11-15',
        end_time: '17:00',
        timezone: 'JST',
        start_date: '2024-11-13',
        start_time: '09:00',
        coordinates: '35.6762,139.6503',
        no_per_purchase: 1,
        type: 'science',
        is_complimentary: false,
      },
    },
    variants: [],
    default_extra_details: {
      venue: 'Tokyo Science Hall',
      end_date: '2024-11-15',
      end_time: '17:00',
      timezone: 'JST',
      start_date: '2024-11-13',
      start_time: '09:00',
      coordinates: '35.6762,139.6503',
      no_per_purchase: 1,
    },
    category: { id: 'cat10', name: 'Science Events' },
    custom_fields: [{ field: 'speaker_count', value: 75 }],
    related_products: [],
    hustle: { name: 'Science Foundation Japan' },
  },
];
